### ISSUE TITLE
unable to run any of the commands

### ISSUE THREAD

**Issue by pirryad** [ruby-journal/cricos_scrape.rb#46]
both institutions or courses present this issue below, I am very new to ruby would appreciate some guidance, thank you.
 
>cricos_scrape scrape institutions
error: undefined method `children' for nil:NilClass. Use --trace to view backtrace

>cricos_scrape scrape institutions --trace
C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scrape/importer/
institution_importer.rb:196:in `block in find_contact_officers': undefined metho
d `children' for nil:NilClass (NoMethodError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1-x86-mingw32/lib/n
okogiri/xml/node_set.rb:187:in `block in each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1-x86-mingw32/lib/n
okogiri/xml/node_set.rb:186:in `upto'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1-x86-mingw32/lib/n
okogiri/xml/node_set.rb:186:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scr
ape/importer/institution_importer.rb:194:in `find_contact_officers'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scr
ape/importer/institution_importer.rb:29:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scr
ape/bulk_import_institutions.rb:22:in `scrape'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scr
ape/bulk_import_institutions.rb:13:in `block in perform'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scr
ape/bulk_import_institutions.rb:12:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/lib/cricos_scr
ape/bulk_import_institutions.rb:12:in `perform'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/cricos_scrape-2.1/bin/cricos_scr
ape:30:in `block (2 levels) in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/co
mmand.rb:178:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/co
mmand.rb:178:in `call'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/co
mmand.rb:153:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/ru
nner.rb:446:in `run_active_command'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/ru
nner.rb:68:in `run!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/de
legates.rb:15:in `run!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/im
port.rb:5:in `block in <top (required)>'

**Comment by runlevel5** [comment]
@pirryad We have not tested this gem on Windows but so far we do not have any issue with Ruby 2.2.0 on Linux.
