### ISSUE TITLE
I guess this is no longer needed

### ISSUE THREAD

**Issue by vaibhavwtg** [ruby-journal/cricos_scrape.rb#47]
Since we have dataAPI and monthly build available, I guess we do not need all of these data

DataAPI : https://data.gov.au/data/dataset/cricos

**Comment by runlevel5** [comment]
@vaibhavwtg yes and no

The DataAPI at the current stage is lacking information (for example contact details). I hope the government will enhance the DataAPI with more features and information.

For the time-being, I highly recommend users to take advantage of both sources. The scraped info can be used to query extra information whilst the DataAPI can be used to develop a full list of courses and institutions.
